Employment_company/urls.py
from django.urls import path
from Employment_company.views import *

app_name = "employ"

urlpatterns = [
    path('', start, name="start"),
    path('registration', registration, name="registration"),
    # path('login',loginHTML,name="login"),
    path('action/<str:link>', user_activ, name="action"),
    path('user_info', user_info, name="user_info"),
    path('updata_user_info', updata_user_info, name="updata_user_info"),
    path('user_login', user_login, name="user_login"),
    path('add_comment', add_comment, name="add_comment"),
    # path('', start, name="start"),
    # path('save_form', save_form, name="save_form"),
    # # path('<str:html_name>', vity_html, name="vity_html")
    path('login_out', login_out, name="login_out"),
    # path('login_or',login_or,name="login_or"),
    # path('user_login',user_login,name="user_login"),
    # path('index', index, name="index"),
    path('deteil/<str:link>', deteil, name="deteil"),

]

ProfiStar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Employment_company.urls")),

]

templates/deteil.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static "script/script.js" %}"></script>
</head>
<body>
<input hidden id ="a_job_id" value="{{ job.id }}">

<a> {{ job.shot_name }}</a>
<br>
<a href="{% url 'employ:start' %}">Назад</a>
<br>

{% for comment in comments %}
    <br>
    <a> -->{{ comment.comment }}</a>
{% endfor %}

<br>
<br>
<a>----------------------</a>
<br>

{% if user.is_authenticated %}
    <form id="comment_form_2">
        {% csrf_token %}
        <table>
            {{ commnet_form }}
        </table>
        <input type="submit" value="Send" >
    </form>

{% else %}
    Не залогиненный пользователь
{% endif %}
</body>
</html>

templates/job_list.html
{% block job_list %}
    {% for job in jobs %}
        <a href="{{ job.get_absolute_url }}"> {{ job.shot_name }}</a>
        <br>
    {% endfor %}
{% endblock job_list %}

templates/main_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static "script/script.js" %}"></script>



</head>


<body>

{% include 'user_form.html' %}

<br>
------------------------
<br>

{% include 'job_list.html' %}

</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static "script/script.js" %}"></script>
</head>
<body>
<form id="id_form">
    {% csrf_token %}
    <table>
        {{ user_form }}
    </table>
    <input type="submit" value="Send" id="send_button">
</form>
<br>
<a href="{% url 'employ:start' %}">Назад</a>
</body>
</html>

templates/user_form.html
{% block user_form %}

    {% if user.is_authenticated %}
        Имя пользователя -> <a href="{% url 'employ:user_info' %}">{{ user.get_username }}</a>
        <br>
        <a href="{% url 'employ:login_out' %}">Выйти</a>
    {% else %}
        <form id="id_login_form">
            {% csrf_token %}
            <table>
                {{ login_form }}
            </table>
            <input type="submit" value="Send" id="send_button">
        </form>
        <a href="{% url 'employ:registration' %}">Регистрация</a>
    {% endif %}

{% endblock user_form %}

templates/user_info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static "script/script.js" %}"></script>

</head>
<body>
    <form id="id_profile_form">
        {% csrf_token %}
        <table>
            {{ profile_form }}
        </table>
        <input type="submit" value="Сохранить" id="send_button">
    </form>



</body>
</html>